language: c
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: "OyoqXO0CqQJpxggE0tNi6LeYXGHslw4SSe4u3UbTOali5AbKdRnSxkMz9YQiuEajJDI2//LZef6RVLULFPZqzIOzsr4yi9S1fbPhXHvqtnZOkpamnkXNNCf7Fd6vGJtT1W140YR9woQoSk0bcLepawSdtkgp+n/ZSqY8rvADgqw="
  matrix:
    - CI_TARGET=doxygen
    - CI_TARGET=clang-report
    - CI_TARGET=translation-report
    - CI_TARGET=vimpatch-report
    - CI_TARGET=doc-index
script:
  - ./ci/${CI_TARGET}.sh
