language: c
env:
  global:
    - DOC_REPO=fwalch/doc2
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: "aUBdo5ITaEGKTDl8LK3LSMcPZmrDXU6TAwv35hBZykkoUkPLCmsrw+X1ZNjlimhwQesCQhl71Ckj7zx+HvJer3IPqnIzAYv3xRgvwVCZNggrBIqTw1oCz+Fw9ZbHefvNXjw2qzyBedE/ge42vI0TOR0TvICUz9OPkt7r6GVjxMs="
  matrix:
    - CI_TARGET=doxygen
    - CI_TARGET=clang-report
    - CI_TARGET=translation-report
    - CI_TARGET=vimpatch-report
    - CI_TARGET=doc-index
script:
  - ./ci/${CI_TARGET}.sh
