sudo: false
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    - NEOVIM_REPO=fwalch/neovim
    - DEPS_REPO=fwalch/neovim-deps
    - DOC_REPO=fwalch/neovim-doc
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: h4cr5Gag69KDU7BCtWTm4YEGNIHdQirRCuJFMu9wgN+7ft0Kimk5Yf1Yj4oR8JD8ddD3yR/afx5ySijWs6KhUNpMyDrk6EsrrYdruLND5jthc5/Uua0QckckjNu8x1EMRC4AavK3E8EJnogwDg/lAMnKNuUTYAAivCNe6hZYHNg=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=assign-labels
    - CI_TARGET=coverity
    - CI_TARGET=deps-src
    - CI_TARGET=doc-index
    - CI_TARGET=doxygen
    - CI_TARGET=nightly
    - CI_TARGET=sync-mirrors
    - CI_TARGET=translation-report
    - CI_TARGET=user-docu
    - CI_TARGET=vimpatch-report
matrix:
  include:
    - os: linux
      env: CI_TARGET=clang-report
      compiler: clang-3.6
    #- os: osx
    #  env: CI_TARGET=deps64
    #  compiler: gcc-4.9
  allow_failures:
    - env: CI_TARGET=coverity
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
    fi
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      # Basic Neovim/test dependencies.
      - autoconf
      - automake
      - build-essential
      - cmake
      - gdb
      - libtool
      - pkg-config
      - unzip
      - xclip
      # Additional compilers/tools.
      - clang-3.6
      - g++-5
      - gcc-5
      - llvm-3.6-dev
cache:
  apt: true
notifications:
  email:
    on_success: never
