sudo: false
language: c
os:
  - linux
compiler: gcc-4.4
matrix:
  include:
    - os: linux
      compiler: gcc-4.5

addons:
  apt:
    packages:
      - gcc-4.4
      - gcc-4.5

script:
  - which $CC
