language: c
env:
  global:
    - DOC_REPO=fwalch/doc
    - secure: Pb3x4zmyRKOGIm0xs0WHvt4k/67WKm4vPLEzr9L9/7AjhDjiE/cDVNZkQRo4dfqaPm8wNYyZrr+QvZZVsiBP30gHymYYUp1An3IhtPSkWIIa8ECTfWhqXCmhxoPL6kdQpCuw0d+8Z+djedrQ7zPKhfPDxH+2JMISJV/2gLjJyRw=
  matrix:
    - CI_TARGET=doxygen
    - CI_TARGET=clang-report
    - CI_TARGET=translation-report
    - CI_TARGET=vimpatch-report
    - CI_TARGET=doc-index

script:
  - ./ci/${CI_TARGET}.sh
