language: c
env:
  global:
    - DOC_REPO: fwalch/doc
    - secure: LHwEucEvWDUJh6xF8txCpjl1DFeHEiMMmaAYkNAqkLfxNqgTxWA9l7m03J8WZeCQBG1u14MKLwZQ5rcUn/nNWJKxm4d7DDvYyBwlqoimPiVlYywXuQOwPON7s3us0S9VyYEMyuBl7zdZoiov7PgKTJNB2qY0LPV23ynUWqxzVjY=
  matrix:
    - CI_TARGET=doxygen
    - CI_TARGET=clang-report
    - CI_TARGET=translation-report
    - CI_TARGET=vimpatch-report
    - CI_TARGET=doc-index
script:
  - ./ci/${CI_TARGET}.sh
