language: c
env:
  global:
    - DEPS_REPO=fwalch/deps
    - DOC_REPO=fwalch/doc
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: LHwEucEvWDUJh6xF8txCpjl1DFeHEiMMmaAYkNAqkLfxNqgTxWA9l7m03J8WZeCQBG1u14MKLwZQ5rcUn/nNWJKxm4d7DDvYyBwlqoimPiVlYywXuQOwPON7s3us0S9VyYEMyuBl7zdZoiov7PgKTJNB2qY0LPV23ynUWqxzVjY=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=clang-report
    - CI_TARGET=coverity
    - CI_TARGET=doc-index
    - CI_TARGET=doxygen
    - CI_TARGET=rebuild-deps32
    - CI_TARGET=rebuild-deps64
    - CI_TARGET=translation-report
    - CI_TARGET=user-docu
script:
  - ./ci/${CI_TARGET}.sh
