language: c
compiler: gcc
env:
  global:
    - GIT_NAME="marvim"
    - GIT_EMAIL="marvim@users.noreply.github.com"
    - NEOVIM_REPO=fwalch/neovim
    - NEOVIM_BRANCH=automatic-deps
    - MAKE_CMD="make -j2"
    - BUILD_DIR=${TRAVIS_BUILD_DIR}
    - NEOVIM_DIR=${BUILD_DIR}/build/neovim
    - DEPS_REPO=fwalch/deps
    - DOC_REPO=fwalch/doc
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: "qANpcGF4WXVqB5At6PSl0m0alE69mTsstyQmV7ORmebohYswlkrF+q32Maz6fc7wuZIDs8xEKrqllw526PhN2PirjM8FNnL3nkEQmu6JzFSra1fMGb72ZMnYIaRkIQs15oaqdcrY4Rwk761fYeu4ZQP+LiNwdI6NuNaYFrBhfvQ="
  matrix:
    - TRAVIS_BUILD_TYPE=coverity
    - TRAVIS_BUILD_TYPE=rebuild-docs
    - TRAVIS_BUILD_TYPE=rebuild-deps
script:
  - ./travis.sh
