language: c
compiler: clang
env:
  global:
    - GIT_NAME="marvim"
    - GIT_EMAIL="marvim@users.noreply.github.com"
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: Eb722ApA4kG+6ZDy7plQzzjam04UUkVYsOMkZQ4uYSfAme4y95pJYUcYks0Zch9psZoHgvq09+iwXDqh9L+YBEYCHog71vNV/tmKBgkPUNdLq4bGSJPA35JKl8sQjKCKRqwNqjJ415sVmUMi9TAe3Gf+6n6w/rEMbV5Wxavn6I8=
  matrix:
    - REPORT=doxygen
    - REPORT=clang-report
    - REPORT=translation-report
    - REPORT=vimpatch-report
    - REPORT=doc-index
script:
  - ./scripts/publish-docs.sh

