sudo: false
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    - NEOVIM_REPO=fwalch/neovim
    - DEPS_REPO=fwalch/neovim-deps
    - DOC_REPO=fwalch/neovim-doc
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: h4cr5Gag69KDU7BCtWTm4YEGNIHdQirRCuJFMu9wgN+7ft0Kimk5Yf1Yj4oR8JD8ddD3yR/afx5ySijWs6KhUNpMyDrk6EsrrYdruLND5jthc5/Uua0QckckjNu8x1EMRC4AavK3E8EJnogwDg/lAMnKNuUTYAAivCNe6hZYHNg=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=clint-errors
matrix:
  include:
    - os: linux
      env: CXX=clang++-3.7 CI_TARGET=clang-report SCAN_BUILD=scan-build-3.7
      compiler: clang-3.7
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
    fi
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - bzr-fastimport
      - clang-3.7
      - cmake
      - g++-4.9
      - g++-5
      - gcc-4.9
      - gcc-5
      - gdb
      - libtool
      - llvm-3.7-dev
      - pkg-config
      - unzip
      - xclip
cache:
  apt: true
  directories:
    - "${TRAVIS_BUILD_DIR}/.deps/build/src"

notifications:
  email:
    on_success: never
